### ISSUE TITLE
[Bug]: Duplicated streams

### ISSUE THREAD

**Issue by mariof1** [Dispatcharr/Dispatcharr#148]
### Describe the bug

I have a playlist that isn't a standard playlist, example below
```
#EXTINF:0 tvg-id="Sky News"  tvg-logo="http://domain.ltd/images/chIcons/123.png"  timeshift="0", Sky News
#EXTGRP:Group Name
http://server.domain.ltd:80/ch123/index.m3u8?token=username.xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxxx
```
Each time when a playlist syncs it creates a new stream but does not remove or overwrite existing streams therefore it produces duplicates.
The issue does not occur with xtream code type playlist or the standard one with the username and password in the url.

### How can we recreate this bug?

Playlist is being added like below
![Image](https://github.com/user-attachments/assets/13c584b7-0671-4f36-8272-4f9fce1ad5d3)

After two syncs I have two additional entries per each stream
![Image](https://github.com/user-attachments/assets/8c66b397-e7a7-46b3-b6f6-a071a45ab3e5)

### Dispatcharr Version

v0.5.2

### Docker Version

v27.5.1

### What's in your Docker Compose file?

```
services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    ports:
      - 9191:9191
    volumes:
      - data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    restart: unless-stopped
volumes:
  data:
```

### Client Information

VLC
