### ISSUE TITLE
Can't add m3u by URL with hostname, only FQDN or IP address

### ISSUE THREAD

**Issue by hidefog** [Dispatcharr/Dispatcharr#63]
In docker, I have several containers that all talk to each other by hostname on an internal docker network.  I would like to add http://ersatztv:8409/iptv/channels.m3u as an m3u to Dispatcharr, but receive the message;
Error
Failed to update M3U account 5: { "server_url": [ "Enter a valid URL." ] }

Using the internal IP instead of the hostname works fine.
http://172.16.1.9:8409/iptv/channels.m3u

I can resolve the hostname from inside the running Dispatcharr container and can wget the url to download the m3u file. I am running Dispatcharr v0.3.2

**Comment by michaelarnauts** [comment]
I've noticed the same. Looking into it further, it's using a Django URLField to validate the input, and it seems that this doesn't allow local hostnames.

See https://forum.djangoproject.com/t/urlfield-not-recognising-domain-port-pattern/34110/3 and further links.

**Comment by hidefog** [comment]
I cheated a little bit to work around this problem, but it's not really a solve for the Django URLField validation issue. I added an alias for a FQDN to the networks: section of my compose.yaml for the specific service I wanted to access internally. Something like this:
```
   networks:
      containers_internal:
        aliases:
          - ersatztv.docker.internal
```

Now I can add http://ersatztv.docker.internal8409/iptv/channels.m3u to Dispatcharr.  It's not exactly what I wanted, but gets me to the same result.

**Comment by yarafie** [comment]
> I cheated a little bit to work around this problem, but it's not really a solve for the Django URLField validation issue. I added an alias for a FQDN to the networks: section of my compose.yaml for the specific service I wanted to access internally. Something like this:
> 
> ```
>    networks:
>       containers_internal:
>         aliases:
>           - ersatztv.docker.internal
> ```
> 
> Now I can add http://ersatztv.docker.internal8409/iptv/channels.m3u to Dispatcharr. It's not exactly what I wanted, but gets me to the same result.

Very interesting, can you share your full compose file for this.

**Comment by hidefog** [comment]
There's really not much more too it.  The compose from the ersatztv stack;
```
services:
  app:
    image: jasongdove/ersatztv:develop-vaapi
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      containers_internal:
        aliases:
          - ersatztv
          - ersatztv.docker.internal
      traefik_proxy:
    tmpfs: /root/.local/share/etv-transcode
    volumes:
      - XXX:/root/.local/share/ersatztv

networks:
  containers_internal:
    external: true
```

And then this is the code in the dispatcharr compose;
```
services:
  app:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.dispatcharr.rule=Host(`dispatcharr.example.com`)"
      - "traefik.http.routers.dispatcharr.entrypoints=websecure"
      - "traefik.http.routers.dispatcharr.tls.certresolver=mydnschallenge"
      - "traefik.http.services.dispatcharr.loadbalancer.server.port=9191"
    volumes:
      - XXX:/data

networks:
  containers_internal:
    external: true
  traefik_proxy:
    external: true
```

Having them both in the same containers_internal network allows them to communicate without opening any extra ports to the outside.  All communications happen internally.  My external clients talk to dispatcharr via Traefik reverse proxy and view the dispatcharr streams through it.
